import { createClientFromRequest } from "npm:@base44/sdk@0.8.40";
import { computeSustainability } from "../../shared/lexPhase3.ts";
import { nowIso } from "../../shared/lexUtils.ts";

// LEX Phase 3 — Sustainability Intelligence. Carbon avoided, shared deliveries,
// bundle savings, vehicle km reduced, and per-corridor monthly trends.
// Read-only; export is generated by the console from the returned rows.
export default async function (req) {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: "Unauthorized" }, { status: 401 });
    if (user.role !== "admin") return Response.json({ error: "Forbidden" }, { status: 403 });

    const [bundles, shipments, carriers] = [
      await base44.asServiceRole.entities.SmartBundle.filter({}),
      await base44.asServiceRole.entities.Shipment.filter({}),
      await base44.asServiceRole.entities.CommunityCarrier.filter({}),
    ];

    const metrics = computeSustainability({ bundles, shipments, carriers });

    return Response.json({
      generated_at: nowIso(),
      ...metrics,
      export_rows: [
        ...metrics.corridor_trends.flatMap((c) =>
          c.monthly_carbon_kg.map((m) => ({
            corridor: c.corridor,
            month: m.month,
            carbon_avoided_kg: m.carbon_kg,
          }))
        ),
        {
          corridor: "network total",
          month: "total",
          carbon_avoided_kg: metrics.carbon_emissions_avoided_kg,
        },
      ],
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}